title: Open Knowledge Graph - Rural Ontology
description: This is the documentation site for my project.
url: "https://sail-ua.github.io"
#remote_theme: rundocs/jekyll-rtd-theme

# Sidebar navigation structure
nav:
  - title: "Home"
    url: "/"
    nav_order: 1
  - title: "PDF Parsing"
    url: "/pdf-parsing"
    nav_order: 2
  - title: "Ontology Construction"
    url: "/ontology-construction"
    nav_order: 3
  - title: "Knowledge Graph Database"
    url: "/knowledge-graph-database"
    nav_order: 4
  - title: "User Interface"
    url: "/user-interface"
    nav_order: 5
