title: My Project
description: This is the documentation site for my project.
url: "https://sail-ua.github.io"
remote_theme: rundocs/jekyll-rtd-theme

# Sidebar navigation structure
nav:
  - title: "Home"
    url: "/"
    nav_order: 1
  - title: "PDF Parsing"
    url: "tree/main/docs/pdf-parsing"
    nav_order: 2
  - title: "Ontology Construction"
    url: "tree/main/docs/ontology-construction"
    nav_order: 3
  - title: "Knowledge Graph Database"
    url: "tree/main/docs/knowledge-graph-database"
    nav_order: 4
  - title: "User Interface"
    url: "tree/main/docs/user-interface"
    nav_order: 5
