# _config.yml
title: My Project
description: This is the documentation site for my project.
baseurl: "/your-repository-name" # for project sites, not needed for user sites
url: "https://your-username.github.io"
theme: minima
